### ISSUE TITLE
include mockup docs and tutorials

### ISSUE THREAD

**Issue by svx** [plone/documentation#1]
include all docs about mockup/toolbar and so on, this goes together with:
https://github.com/plone/mockup/issues/279

**Comment by svx** [comment]
@polyester

@fulv you started to work on that during PLOG 2015 right ?

**Comment by fulv** [comment]
Yes, I'm still working on it.

**Comment by svx** [comment]
cool !!!!!!!

**Comment by ebrehault** [comment]
Hi @svx and @fulv,
I do not know what is the status on this issue, but we definitely need to document Mockup pattern usage in the Plone doc.
I am not sure getting the full content of http://plone.github.io/mockup/dev/# makes a lot of sense because a lot of patterns are internal to Plone (almost nobody will re-use Theme mapper pattern or the Structure pattern for a custom dev).
Moreover mixing a JS/markdown-based doc and a RST/python-based doc sounds tricky.

So I think we should have a regular doc page here (written manually) explaining how to use the main patterns (like modal, content-loader, moment, etc.).

What do you think?

**Comment by stevepiercy** [comment]
Closing in favor of https://github.com/plone/documentation/issues/1270 and https://github.com/plone/documentation/pull/1253
