### ISSUE TITLE
Branch clarification 

### ISSUE THREAD

**Issue by svx** [plone/documentation#1025]
@polyester would you mind to shine some light on the branches ?

I am getting confused with the *5.2* and the *5.2py3* branch.

Why we need two, this makes IMHO merging/improving way more complicated ?

What is the idea behind having two 5.2 branches ?

**Comment by polyester** [comment]
5.2 is the branch I created. 

5.2py3 branch was a temporary branch, created off that, to work on the update docs. It should have been deleted after it was merged into 5.2. I think I forgot that, because it was still a work-in-progress then.

I'll delete it now. If people want to update the WIP-documentation, they should create a new temp branch off of 5.2.

**Comment by polyester** [comment]
ah the pull request wasn't merged yet, because I didn't want to merge my own.

**Comment by polyester** [comment]
merged into 5.2 now, and closed the 5.2py3 branch.
