### ISSUE TITLE
Add hint to contributors guidelines: How to mark a section that needs some content or just reviewing.

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1165]
````
```{admonition} TODO
:class: warning

Add content for this section
```
````

![image](https://user-images.githubusercontent.com/1144737/150936964-2b6364d7-6e25-4f4f-a188-2aab4adff383.png)

**Comment by stevepiercy** [comment]
`sphinx.ext.todo` should handle this.

````
```{todo}
Perhaps some of this introduction should be an include, so we don't have to repeat ourselves?
```
````

![Screen Shot 2022-01-25 at 5 10 40 AM](https://user-images.githubusercontent.com/102112/150982878-e300b1e9-08db-41e0-b1e9-2f394cc1e2d5.png)

We need to adjust the style sheet so that it does not use the default admonition style, but instead the class `admonition-todo`.

```html
<div class="admonition-todo admonition" id="id1">
<p class="admonition-title">Todo</p>
<p>Perhaps some of this introduction should be an include, so we don't have to repeat ourselves?</p>
</div>
```

**Comment by stevepiercy** [comment]
See also the docs for the extension:

https://www.sphinx-doc.org/en/master/usage/extensions/todo.html

**Comment by stevepiercy** [comment]
I proposed a fix in https://github.com/plone/documentation/pull/1166#discussion_r795304957
