### ISSUE TITLE
Navigation: Show current position in navigation

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1257]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

Would be nice to have the current navigation entry in scope.
Example: https://6.dev-docs.plone.org/plone.api/api/content.html
![grafik](https://user-images.githubusercontent.com/1144737/170118447-fd5c3ef6-85ed-4683-bc4f-135c01713233.png)

**Comment by stevepiercy** [comment]
I agree. Is there something that auto-scrolls the navigation pane in any of the base themes? I would assume that this problem has been identified with possible solutions already in their issue trackers.

**Comment by stevepiercy** [comment]
This was fixed in the grandparent theme https://github.com/pydata/pydata-sphinx-theme/issues/535.

Demo https://pydata-sphinx-theme.readthedocs.io/en/latest/demo/subpages/subsubpages/subsubpage20.html

This was incorporated in [v0.3.2 of sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme/commit/f425732ea1c2dd2f1a1ddaf0a89413a14b981baa#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R26), which we [pinned to <=0.3.99](https://github.com/plone/documentation/blob/6-dev/requirements.txt#L8), so it should work.

**Comment by ksuess** [comment]
Bug fix in sphinx-book-theme is submitted: https://github.com/executablebooks/sphinx-book-theme/pull/609

**Comment by ksuess** [comment]
> Bug fix in sphinx-book-theme is submitted: [executablebooks/sphinx-book-theme#609](https://github.com/executablebooks/sphinx-book-theme/pull/609)

Bug fix is merged, but no release so far. https://github.com/executablebooks/sphinx-book-theme/issues/611
I'll make a patch here and in training.
