### ISSUE TITLE
Two times a glossary?

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1337]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

There is an overall glossary and one in in the restapi chapter. This is confusing and the restapi one should get merged into the main glossary.

**Comment by stevepiercy** [comment]
Just to clarify, we should keep both Glossaries, because restapi has its own separate build as a separate product. We should merge the Glossary entries from `plone/plone.restapi` into those of `plone/documentation`.

Then in the main docs, we should ignore the `glossary.md` in the `plone/plone.restapi` folder.

We should do the same for volto and plone.api.

**Comment by stevepiercy** [comment]
This was a little maddening to figure out, but it turns out to be simple.

In `submodules/plone.restapi/docs/source/index.md`:

```diff
- glossary
+ /glossary
```

In `documentation/docs/conf.py`, in the `exclude_patterns` list:

```diff
+    "plone.restapi/docs/source/glossary.md",  # There can be only one Glossary.
```

I verified builds in both restapi and main docs.
