### ISSUE TITLE
Search results (Algolia) of 5.docs.plone.org should point to 5.docs.plone.org not docs.plone.org

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1375]
### Plone Documentation versions affected

- [X] 5.x
- [ ] 6.x

### Description

[5.docs.plone.org](https://5.docs.plone.org/)

**Comment by ksuess** [comment]
Maybe I am wrong, but I think, @acsr has been working on Algolia search in Plone 5 documentation.

**Comment by acsr** [comment]
also involved: @polyester, @balavec , @pbauer see Sprint report at @kuz https://docs.google.com/document/d/1NL07cxHo62yqpGmUqYZk7IeG0N9m6HOpEhSXYKRIeCk/edit#heading=h.e154b6resuuu

**Comment by stevepiercy** [comment]
We decided to revert to the default Sphinx search, as we were unable to recover access to the Algolia account and configuration. Closing.

**Comment by acsr** [comment]
@stevepiercy The old local self managed scraper I used in the setup I suggested was Python2 based. The original Plone setup was dependent on the docsearch scraper run by algolia (that was reported by @svx to me) Algolia changed the setup and API recently. When I jumped in, Algolia was already in place for docs.plone.org but misconfigured. We got our experience from other projects. What we did in Ferrara was improving the UI Setup (CSS etc.). No idea what came later. There was another issue later. At the end there was no link for full search resuklts, leading to limitations if the needed result was deeper in the tree.

The Sphinx search was crap and offered no proper context. Need to check how this improved since then. Hope we find a solution using [nuclia](https://nuclia.com/) soon. Times change and Algolia was great in 2017 but now we need more up to date stuff. It is crucial for Plones success.

**Comment by stevepiercy** [comment]
@acsr have you tried the docs search recently? @ksuess made some improvements to allow filtering by topic.

GSoC accepted our Nuclia search project across Documentation and Training, and we have a mentee for it. We'll be transparent with its development, and welcome feedback, once we start creating issues and a project board for it.
