### ISSUE TITLE
Please Recommend Podman

### ISSUE THREAD

**Issue by muellert** [plone/documentation#1578]
### Description

Several pieces of Plone documentation revolving around installation recommend docker, but for a number of reasons, docker is falling out of favour with big Linux distros. Please add/modify the documentation to point to Podman as an alternative, which has a similar feature set, but does not require root, and which also seems to have less licensing problems.

**Comment by stevepiercy** [comment]
> docker is falling out of favour with big Linux distros.

Citation, please, so I can read about this and become more informed.

> Please add/modify the documentation to point to Podman as an alternative,

This already exists: https://6.docs.plone.org/install/index.html?highlight=podman#containers

> which also seems to have less licensing problems.

There has been concern and discussion about Docker licensing at https://community.plone.org/t/docker-and-containerized-plone-volto-on-virtual-machines/16578. IMO, the concern can be assuaged by paying for Docker and complying with its license, if needed. It's not clear to me what is needed, although there is no shortage of speculation.

Much of our infrastructure and cookiecutters use Docker now, and our documentation reflects that. Infrastructure drives documentation, because the people who are on the @plone/ai-team write it. They also conduct [Trainings](https://training.plone.org/plone-deployment/index.html) at PloneConf every year. Switching from Docker to another OCI-compliant container engine would require significant effort with little net practical gain.

Assuming you would like to see your request happen, I would suggest the following steps.

1. Create a project repo that replicates the functionality of https://github.com/collective/cookiecutter-plone-starter which is in the process of getting migrated to https://github.com/plone/cookiecutter-plone. I would suggest either putting it under either your own GitHub account or the [collective GitHub organization](https://github.com/collective).
2. Write documentation of how to install and develop Plone with Podman. The Documentation Team is working on reorganizing docs to include contributions such as alternative how-to guides, and this would be a welcome addition.
3. Post to the Community Forum with your request. Here is one relevant post: https://community.plone.org/t/plone-6-with-podman/16008.
4. Do a training for how to use Podman at an upcoming [Plone event](https://plone.org/news-and-events/events).

I'm closing this issue as won't fix. I would encourage you to pursue the above suggestions.
