### ISSUE TITLE
Clarify install methods to either "Create a project" or "Contribute to a package"

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1598]
### Links of affected pages in Plone Documentation, if any.

- [Install](https://6.docs.plone.org/install/index.html)
- [Containers](https://6.docs.plone.org/install/containers/index.html)
- [Install Plone from its packages](https://6.docs.plone.org/install/install-from-packages.html)

### Description

The Plone install story lacks clarity.

For Volto we reached the conclusion that you either want to install Volto for a _project_ or to _contribute_ to it and updated its documentation accordingly.

- [Develop Volto core](https://6.docs.plone.org/volto/contributing/developing-core.html)

We want to adopt this framing of installation for the entirety of Plone.

As a side note, we also promote using [Containers](https://6.docs.plone.org/install/containers/index.html) as an installation method. This should be demoted as an alternative installation method until both we clearly define the use cases for using containers over packages and the following issues and pull requests are resolved.

- https://github.com/plone/documentation/issues/1434
- https://github.com/plone/documentation/issues/1360
- https://github.com/plone/documentation/issues/1358
- https://github.com/plone/documentation/issues/1349
- https://github.com/plone/documentation/issues/1314
- https://github.com/plone/documentation/pull/1456

For Plone itself, we cannot make a distinction between Create a Plone project and Contribute to a Plone package because Plone is not a single package but consists of _all_ of its packages, each of which may have its own story for contributing. For Plone itself, we should update [Install](https://6.docs.plone.org/install/index.html) as follows.

- [x] Replace text under under [Install](https://6.docs.plone.org/install/index.html) with the following: "In this part of the documentation, you can find how to try Plone or how to install Plone to either _Create a Plone project_ or _Contribute to a Plone package_."
- [x] Demote Containers to the last item under the Install navigation.
- [x] Demote Containers below Packages.
- [ ] Define use cases for when containers is preferred over packages, and conversely packages over containers.
- [x] In [Getting started](https://6.docs.plone.org/install/index.html#getting-started), move "Try a demo" into narrative text as a sub-heading under [Install](https://6.docs.plone.org/install/index.html).
- [x] In [Getting started](https://6.docs.plone.org/install/index.html#getting-started), remove the Install content.
- [x] In [Getting started](https://6.docs.plone.org/install/index.html#getting-started), create two new cards, "Create a project" and "Contribute to a Plone package". Each should have sufficient information to guide developers on the correct path, mentioning "The [Training](https://training.plone.org/) you do should specify which path to follow."
- [x] "Create a project" should refer to [Install Plone from its packages](https://6.docs.plone.org/install/install-from-packages.html) (and possibly [Containers](https://6.docs.plone.org/install/containers/index.html), although I am not yet convinced this is a good path).
- [x] "Contribute to a Plone package" should be a new section that consists of an introduction and a link to [Contributing to Plone](https://6.docs.plone.org/contributing/index.html).

Feedback appreciated.

**Comment by stevepiercy** [comment]
@07tAnYa please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

**Comment by davisagli** [comment]
@stevepiercy In general this sounds like a good path (certainly an improvement over the status quo).

I hate the title "Install Plone from its packages". What does "from its packages" mean? You get the packages either way, it's a question of how you get them. "Create a Plone project" would be a better title for this chapter (with an implicit "using cookiecutter", but we don't have to say that in the title).

I would like to get rid of the Containers install section entirely, except that there's some information in its sub-pages which should get moved into the deployment section rather than removed entirely. So, demoting it is fine as a first step. Even in the use cases where it makes sense to run Plone in containers, no one should be doing it the way shown on https://6.docs.plone.org/install/containers/index.html. They should create a project using the cookiecutter, and then use the commands it creates in the project for running containers.

I like the proposal to have 2 cards "Create a project" and "Contribute to a Plone package", to emphasize that distinction. I would put the links to contribute to the various packages in the intro to https://6.docs.plone.org/contributing/index.html rather than inline in the card under Getting Started, but I don't have a strong opinion about that.

We are missing a "Contributing to Plone backend packages" section for how to contribute to Python packages other than plone.rest and plone.restapi

**Comment by stevepiercy** [comment]
> I hate the title "Install Plone from its packages". What does "from its packages" mean? You get the packages either way, it's a question of how you get them. "Create a Plone project" would be a better title for this chapter (with an implicit "using cookiecutter", but we don't have to say that in the title).

I never liked it either. It makes more sense to say _what_ you want to do, not _how_ you can do it.

> I would like to get rid of the Containers install section entirely, except that there's some information in its sub-pages which should get moved into the deployment section rather than removed entirely. So, demoting it is fine as a first step. Even in the use cases where it makes sense to run Plone in containers, no one should be doing it the way shown on https://6.docs.plone.org/install/containers/index.html. They should create a project using the cookiecutter, and then use the commands it creates in the project for running containers.

Agreed. Most of the containers sub-pages are recipes or "how-to guides", and definitely not oriented toward installation.

I have been asking for use cases for, or why someone would follow, https://6.docs.plone.org/install/containers/index.html. I really don't know.

> We are missing a "Contributing to Plone backend packages" section for how to contribute to Python packages other than plone.rest and plone.restapi

There is [Specific contribution policies of projects](https://6.docs.plone.org/contributing/index.html#specific-contribution-policies-of-projects).
