### ISSUE TITLE
to symlink or not to symlink README.rst?

### ISSUE THREAD

**Issue by fulv** [plone/documentation#226]
In about/documentation_styleguide_addons.rst there is a bit of contradictory information:

* in line 33, it says that "creating a README.rst in the /docs/source directory, and making a symlink to it from the root of your repository, then pypi will not render it nice"
* but in line 58, "If you want that information to also be available in the documentation on docs.plone.org, you should move those files (README.rst and CHANGES.rst) into the /docs/source directory, and then make a symlink in the root of your package

/me confused.

**Comment by svx** [comment]
I am too, @polyester was working on that, @polyester can you bring some light into this ?

**Comment by polyester** [comment]
yeah, that's a problem. Github will do the right thing, but PyPi will just show .rst files as-is, without any rendering, if it's a symlinked file.

So that needs updating. If the guidelines are followed, a readme.rst should *not* change often, and be short, so best practice may be 

- to put a short readme.rst both in the top folder and the docs folder
- to keep the changes.rst in the docs folder

but it does have the drawback of having readme.rst duplicated. I'll try to write a consistent guide.

**Comment by svx** [comment]
Doing some research ... it seems also related to the version of docutils and 'proper' rst [github and sphinx are not always using 'real' rst.
There is for example a rst-lint checker:

https://pypi.python.org/pypi/restructuredtext_lint

I did not tried it, yet.

**Comment by gforcada** [comment]
Sphinx can reference files outside the docs folder, so wouldn't make sense to keep both README.rst and CHANGES.rst at top level? This way setup.py is more dumb proof (i.e. for the crazy one changing them to .rst aka me :D) and you access them from github directly within one click.

**Comment by svx** [comment]
Yes, Sphinx can that, but this will not help in that case, the probelem is the rendering from rst on pypi,
Pypi is using and wired setup of old docutils with some crazy filtering, so pypi is filering outcertain rst from for example Sphinx, that i sone reason why sometimes your readme.rst is not showing on pypi, at least that is what I found out during my reasearch yesterday.
So imho, we need to find a way to make sure that all rst is valid rat, before people push their eggs.
Or do I getting it wrong ?

**Comment by tisto** [comment]
FYI: We had a long discussion where to put README/CHANGES and changed all core packages accordingly:

https://github.com/plone/plone.api/issues/111

Isn't is possible to make the documentation just fetch README.rst and CHANGES.rst from the top-level in addition to the docs folder?

**Comment by polyester** [comment]
@tisto yes that would be possible. It's a teeny tiny bit more configuration on our side, but it does give a more consistent approach. And since including an add-on into the docs.plone.org isn't such a regular event, I'd say it is worth it.

**Comment by svx** [comment]
Do do that we will have to rewrite https://github.com/plone/papyrus/blob/master/get_external_doc.sh in a way that the script is checking for the readme in /top-level.

We can do that but before we start we should make sure that **all** docs we include form own repos, which are for the moment:

- https://github.com/plone/plone.app.dexterity
- https://github.com/plone/plone.api
- https://github.com/plone/plone.app.robotframework
- https://github.com/plone/plone.app.multilingual
- https://github.com/plone/diazo
- https://github.com/collective/tutorial.todoapp
- https://github.com/plone/Products.TinyMCE
- https://github.com/plone/plone.app.contentlisting
- https://github.com/plone/plone.app.contenttypes
- https://github.com/plone/plone.app.theming
- https://github.com/plone/plone.app.testing
- https://github.com/collective/collective.transmogrifier
- https://github.com/plone/plone.app.caching
- https://github.com/plone/ansible-playbook
- mrbob.plone-templates

follow this, otherwise we will end up which a **huge** mess with nobody are able to maintain.

I purpose this for Plone5 docs, because I think we are not able to reach that for Plone 4

**Comment by svx** [comment]
I really would like to propose a 'standard layout' for repositories, like the remae goes into top-level and docs go into /docs, not 'only' best practices more something in the lines of that it our guideline on how we do that, can we do something like that, looking also at @esteele  :)

**Comment by esteele** [comment]
Yes, please. Consistent naming and structure for at least the readme and changelog would make my life easier.

**Comment by svx** [comment]
follwoing up that means we will go for a structure like:

$repo: README.rst, CHANGES.rst /docs right ?

meaning we have in the top level the files README, CHANGES and the dir /docs 

@polyester would you mind to update 'best practices' in the docs ? :)

**Comment by gforcada** [comment]
:+1: on that, now we need some scripts on jenkins to report about that and p.r.codeanalysis to warn about it

**Comment by svx** [comment]
@gforcada +1, yes !!!!

**Comment by svx** [comment]
@gforcada and a check on jenkins to give a general overview ? I opened already a issue for that :)

**Comment by gforcada** [comment]
@svx can you assign that one to me I really lost tracks of issues on github...

**Comment by svx** [comment]
done

**Comment by polyester** [comment]
Yep, I'll do it, but needs some more thinking, now is the time to do that. If we are going to change and adapt the recommended file layout for add-ons, let's take a little moment to get it right...

Some things to consider:

- [ ] do we really need/want a /docs/source directory? Some already don't have it, and we're pulling in the whole /docs in anyway. It is overkill for those without any Sphinx, and not a hindrance for those with own Sphinx installs. Just /docs is probably clearer.
- [ ] A subfolder "/docs/resources" is probably better than /docs/_images, as we're now recommending. That's awkward, and also not very extendable. You know: PDF, video, audio, images.
- [ ] People should include a comment (http://docutils.sourceforge.net/docs/user/rst/quickref.html#comments) so it becomes clear where the docs  for their add-on can be updated. Something like "If you are reading this on docs.plone.org: the source for this add-on documentation lives at https://github.com/collective/collective.fancystuff"
- [ ] Let's then also put a LICENCE.rst in there.

**Comment by svx** [comment]
+1 !

**Comment by svx** [comment]
Since we have now the new guideline, do we have to adjust https://github.com/plone/papyrus/blob/master/get_external_doc.sh ?

**Comment by polyester** [comment]
yep, but gradually, one by one, if and when the external repos change to the new standard

**Comment by svx** [comment]
I just found 'another' issue since people tend to use all these badges like travis and code coverage like this:

.. image:: https://secure.travis-ci.org/plone/bobtemplates.plone.png?branch=master
    :target: http://travis-ci.org/plone/bobtemplates.plone

.. image:: https://pypip.in/d/bobtemplates.plone/badge.png
    :target: https://pypi.python.org/pypi/bobtemplates.plone/
    :alt: Downloads

.. image:: https://pypip.in/v/bobtemplates.plone/badge.png
    :target: https://pypi.python.org/pypi/bobtemplates.plone/
    :alt: Latest Version

.. image:: https://pypip.in/egg/bobtemplates.plone/badge.png
    :target: https://pypi.python.org/pypi/bobtemplates.plone/
    :alt: Egg Status

.. image:: https://pypip.in/license/bobtemplates.plone/badge.png
    :target: https://pypi.python.org/pypi/bobtemplates.plone/
    :alt: License

Our approach is not working really well, sorry, I just tried to get that working for bobtemplates.plone for more than an hour, but so far no chance to solve this nice.

Further, adjusting our script for fetch external docs, is with the new approach kind of messy, at least what I tried so far.
I guess we have to go back to thinking about a other solution, for me it looks like including the readme will not work in a clean and nice way for above reasons.

**Comment by svx** [comment]
This is how it looks like now:

![bobtemplates_readme](https://cloud.githubusercontent.com/assets/358860/7631552/05fe0b94-fa44-11e4-8e99-fda10ee99a1b.png)

**Comment by polyester** [comment]
with https://github.com/plone/papyrus/commit/698cc160fbeb62fc78fd35ee64be0025f93545d6 we pull in README.rst and CHANGES.rst now. 

As for the perceived ugliness of the badges, we could ask authors to encase them in a 
.. class:: badges

statement, and then hide them with CSS on docs.plone.org, while they would still happily pop up on their respective github repositories.

**Comment by mauritsvanrees** [comment]
For the record: I declare a total ban on symbolic links in packages. We had a problem today on the coredev 4.3 branch with a fresh plone.locking 2.0.6 release. README.txt was missing. What it in the end boiled to was: in git there was a symbolic link from rst to txt, and in the source distribution tarball it was the other way around.

This is actually only a problem for very old setuptools versions. 0.6c11 fails, 1.4.2 is fine.

At first it seemed only a problem on Python 2.6, but during testing I also saw it with Python 2.7.

In case you want to test it, here is a buildout.cfg:

```
[buildout]
parts = test
versions = versions
download-cache = downloads
eggs-directory = eggs

[test]
recipe = zc.recipe.egg
interpreter = maurits
eggs = mauritstestpackage

[versions]
mauritstestpackage = 0.6
setuptools = 0.6c11
#setuptools = 1.4.2
zc.buildout = 1.7.1
zc.recipe.egg = 1.3.2
```

**Comment by tisto** [comment]
+1 for disallowing symlinks and upgrading setuptools for Plone 4.3.

**Comment by svx** [comment]
As you can see here: http://docs.plone.org/about/documentation_styleguide_addons.html#readme-example we are not mention symlinking your readme :) so yes +1 !

**Comment by svx** [comment]
I guess I can close this, right ?

**Comment by fulv** [comment]
@svx +1
