### ISSUE TITLE
Release information on each page?

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#236]
Just after merging #234 I thought that if we have a way (Sphinx maybe has it already?) to annotate sections to be relevant for one or another version (the ``since:`` in terms of API methods) it would make these cleanup tasks like #234 far easier...

**Comment by svx** [comment]
Yeah, we could do that with:

http://sphinx-doc.org/markup/para.html

see the sections:

- versionadded
- versionchanged
- deprecated

**Comment by svx** [comment]
Btw, this is in general not a problem since we use different branches for different versions, we have this sometimes because we branched 3 docs out of the 4 docs, because we had no real versions before.

Anyway we should add this to best practices of writing docs, because in some cases it could be handy, for example the move from paster to bobtemplates :)

**Comment by svx** [comment]
Yes we are using some of this tags now and so far it is nice to have them !
