### ISSUE TITLE
External documentation must respect versions from coredev/ release

### ISSUE THREAD

**Issue by jensens** [plone/documentation#275]
**Story**

I have this PR #192 open and in there we figured out to better include ``buildout.coredev`` documentation instead of repeating ourselves here. 

So I tried to add the buildout.coredev/docs to ``externals.txt`` like this:

``https://github.com/plone/buildout.coredev.git,source/documentation/develop/coredev``

**Problem**

This fetches the 4.3 docs (because its set as default branch). I don't see a way to set the branch to 5.0.

This is valid for all external packages.

**Criticism**

- We have no version pinning for documentation.
- I have no idea why we invent a new way to fetch things from git. Its like reinventing the wheel.

**Ideas/ solution**

Why don't we use ``mr.developer`` and the sources files in buildout.coredev? For some (what we consider core docs?) we already do.

- read sources file from buildout.coredev in the version needed (buildout extends)
- provide checkouts file for the to-be-included sources.
- or take eggs from releases and fetch docs from there (i'd prefer this much to have docs matching the release and additional '4.3-latest' + '5.0.-latest')
- have some mini-recipe to symlink the stuff (or some script)
- symlink docs folders to the locations in source tree? 
- no git fights with sparse (worked for some reason not on my maschine/ git version)

**Comment by svx** [comment]
Hi,

Ok let me explain:

We *do* have versions of the docs for different versions of plone, all of this is done in https://github.com/plone/papyrus here we have branches for version 3,4,5 and in this branches is also configured which version of the docs should be pulled, this is maybe not ideal but it is proven to work.

Release of docs have also a git tag, at least that is on our list, but there tagged with the release date of the docs, and the reason for that is,with that tag, the build server builds automatically pdfs, zeal/dash/, docker cts and lots of other stuff.

Git-sparse is in git since version 1.7 in the ubuntu world that means since 12.04, I am quite sure that you are developing on a newer version :)

This said, I completely agree spars is not perfect, and it is sometimes hard to use, but it is also not something what is rare to use, it works.    

Some other points you mentioned are really interesting and I certainly would like to test them, but please keep in mind, the docs 'core' team is quite small we are two people at the moment, so we simply have a time issue.
Second, we also have to keep in mind, that not all of the user are developers, so we also have to try to think as a user, this is hard, but the docs in general are not developer only, this may not be the case for core devs, but imho we have to find a sane way to work on both equal easy.

At the end I also want to say, that the whole docs project is also, like the readme of papyrus says, work in progress and we are learning and figure things out all the time, and yes sometimes we do not get it right straight form the beginning, but at least when I look what we currently have and how other projects doing it [as we talk and work together with other docs writers, even with professional ones] we maybe not perfect but we also not doing that bad.

**Comment by jensens** [comment]
Indeed, this is a papyrus thing, so wrong at this place.
I'll summarize and move over there.
