### ISSUE TITLE
develop/plone-coredev

### ISSUE THREAD

**Issue by svx** [plone/documentation#300]
Needs review and updates:

- remove links to dev.plone.org
- update plips
- move other languages than engl. to translation
- check if that is an external include

**Comment by jensens** [comment]
this should point to the buildout.coredev information of 5.0 branch - but without changes in papyrus we can only point to master branches of external documentation at the moment.

The papyrus branch "jensens-external-refactoring" tries to adress all the problems and offer a more declarative solution than the current.

**Comment by polyester** [comment]
I'm starting to like the 'jensens-external-refactoring' branch, and get the numbering system also. Only thing I would like (niggle...)

- if we could somehow make sure the symlinked repos that are symlinked into 'documentation' end up in source/documentation/.gitignore 

I know they could be put in by hand, but that's error-prone and at some point somebody is going to check a whole sub-repo into github.com/plone/documentation

**Comment by svx** [comment]
That is great that you get the numbering system, I am really happy for you.

As I said before I like it too, but I do not get for example the numbering system and also I do not get some other stuff.

In short as I also wrote as a comment before it would be ice to have more documentation how this whole setup works, if you get the setup maybe you would like to write more docs about it.

**Comment by jensens** [comment]
The numbering system is just about order of execution, since there is no order in buildout cfg files key/value assignments. 

Execution order is important, because it builds a tree and you cant symlink at non-existent places.
x-COMMAND is executed before the other x-{PACKAGENAME}.

This information is used to generate a script which is then executed as a command. I fact it does partly the same as the get_external_doc.sh - but does it for all documentation parts and in a declarative way.

adding the repos to .gitignoire is for sure possible. i can add this feature to the genshi template if you decide to go this path.

**Comment by jensens** [comment]
@svx, we can have a hangout and i try to explain interactive.

**Comment by polyester** [comment]
closed via https://github.com/plone/papyrus/commit/85431194f301caa9f6154588461ebd375e114f6f
