### ISSUE TITLE
remove lingual plone stuff

### ISSUE THREAD

**Issue by svx** [plone/documentation#323]
- remove all lingual.plone stuff from Plone 5 docs

**Comment by polyester** [comment]
The following pages need review from @bloodbare or @sneridagh , to state the p.a.m. version of things.

- [ ] https://github.com/plone/documentation/blob/5.0/develop/plone/i18n/cache.rst (it can probably go completely, but double check
- [ ] https://github.com/plone/documentation/blob/5.0/develop/plone/searching_and_indexing/query.rst (mentions LinguaPlone 5 times...)
- [ ] https://github.com/plone/documentation/blob/5.0/develop/plone/i18n/language.rst

rest of mentions are taken care of in https://github.com/plone/documentation/issues/344

**Comment by sneridagh** [comment]
1. https://github.com/plone/documentation/blob/5.0/develop/plone/i18n/cache.rst can go away because it's something that can be done from varnish itself (unset the cookie for some resources).
2. https://github.com/plone/documentation/blob/5.0/develop/plone/searching_and_indexing/query.rst @bloodbare should review it to be sure.
3. https://github.com/plone/documentation/blob/5.0/develop/plone/i18n/language.rst the mentions are valid, but should refer to p.a.m instead of LinguaPlone. It should be reviewed as well since it's possible that some reference in code is wrong.

**Comment by svx** [comment]
@bloodbare could you review https://github.com/plone/documentation/blob/5.0/develop/plone/searching_and_indexing/query.rst if you have a minute or two ? Would be great to have that in the 5.1 docs ! :)

**Comment by svx** [comment]
@polyester @sneridagh Who would be the right person to review: https://github.com/plone/documentation/blob/5.0/develop/plone/i18n/language.rst ?

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5. We now have https://6.docs.plone.org/i18n-l10n/index.html and https://6.docs.plone.org/volto/development/i18n.html. We don't have good search docs yet, though, but we have an open issue for it at https://github.com/plone/documentation/issues/1730
