### ISSUE TITLE
Update nginx docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#448]
Meta ticket for updating our nginx docs
- [ ] move install and configuration via buildout into a separate file
- [ ] update nginx config to modern and best practices
- [x] rewrite part about ssl, add good example
- [ ] ssl: add links to ssllabs
- [ ] add picture of a good ssllabs ranking
- [ ] ssl: add links and howto about configs and help pages
- [ ] /var/www is old style, mention also /srv 
- [ ] better docs about certs also mention https://letsencrypt.org/
- [ ] fix old section "By using cookies" under "Session affinity"

**Comment by tkimnguyen** [comment]
I started by adding in an nginx SSL config, in https://github.com/plone/documentation/tree/update_nginx

**Comment by stevepiercy** [comment]
The section "By using cookies" under "Session affinity" is very old, and links to a no longer maintained repository for [nginx sticky session module](http://nginx-sticky-module.googlecode.com/files/nginx-sticky-module-1.0-rc2.tar.gz). The correct link is https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/overview, but since I'm not familiar with the process that is documented, I left it alone.

**Comment by tkimnguyen** [comment]
@stevepiercy I added that to the checklist - thx

**Comment by stevepiercy** [comment]
Closing as fixed. There are many ways to configure nginx, depending on frontend, and now Traefik has become the latest and greatest.
