### ISSUE TITLE
Remove varnish 2 docs ?

### ISSUE THREAD

**Issue by svx** [plone/documentation#460]
Varnish 2 is a 'bit outdated' by now, should we remove the old varnish 2 parts or should we move them to 'old', having them in the main docs document feels a bit outdated, all major OSs give you now varnish 3 via package manager, some even started to give you varnish 4.

Ubuntu 14.04 is giving you 3, since all our docs are based on that I say we keep 3 but remove/move varnish 2 ?

**Comment by fulv** [comment]
(FWIW - Ubunty 15.04 comes with Varnish 4.)

**Comment by gforcada** [comment]
At most I would keep it for Plone 3 docs, as maybe some websites are still stuck on that version and the same with the server (everything done and locked since +5 years and scared/not bothered to touch it ever again).

Also FWIW plone.recipe.varnish is still using varnish 3 (I guess 2 as well) and only the 2.x beta version (no stable so far on pypi) has support for Varnish 4.

**Comment by svx** [comment]
@fulv what you want to say with that ?

@gforcada I do not want to remove v3 from the PLone 5 branch just v 2 :)

**Comment by fulv** [comment]
I was just saying that it's getting harder to even use 3, let alone 2.

**Comment by svx** [comment]
@fulv ah, yes !

14.04 still ships with 3, since the rest of the docs are based on 14.04 I would suggest to keep 3 till we decide to base the docs on the next LTS

**Comment by fulv** [comment]
I have no objection to that, but we'll want to revisit that when the next
LTS release comes out (16.04 maybe?).

**Comment by svx** [comment]
Yes, sure !

Usually we move to the next LTS, when there is the first version bump, so that would be 16.04-01, because in general with that release all the small 'itches' from the release version are fixed :)

**Comment by smcmahon** [comment]
If we want to have a VCL 4 sample, I'm willing to add one. I would base it on https://github.com/plone/ansible-playbook/blob/master/roles/varnish/templates/default.vcl4.j2

**Comment by plone-foundation** [comment]
HI,
we already have that :)

http://docs.plone.org/manage/deploying/caching/varnish4.html

but maybe you can check and if necessary improve that ?

**Comment by cleberjsantos** [comment]
@svx  +1 I think we should move v2 to 'old'.

@gforcada Yes, plone.recipe.varnish is still using varnish 3, but have the 2.x beta version (no stable so far on pypi) has support for Varnish 4. 

Not yet stable because we not have many people making use in the Plone with v4, and they are also not returning with feedback about.

**Comment by hvelarde** [comment]
old Varnish stuff was killed.
