### ISSUE TITLE
Docker based installation documentation

### ISSUE THREAD

**Issue by avoinea** [plone/documentation#524]
Now that we have a working Docker image for Plone at https://hub.docker.com/r/plone/plone and soon an Official one (docker-library/official-images#1434 and docker-library/docs#484) we should also document Docker based installation within this documentation, or at least add a link to http://hub.docker.com/r/plone/plone

**Comment by svx** [comment]
yes, but first we should fix: https://github.com/plone/plone.docker/tree/master/docs so that everything there is awesome and than we add the link to the docs.

we are currently missing at least:
- index.rst
- moving building to its own : building.rst, which also should include best practices, docker-lint and stuff like that
- document and fix: https://github.com/plone/plone.docker/issues/7
- add docs about  running it without docker-compose, add stuff like systemd and so on, not everyone is using docker-compose [in production]
- for docker-compose: add link to docs about it
- ...

**Comment by svx** [comment]
@avoinea where would be a good place to add it on the docs, strictly technical speaking putting it under _http://docs.plone.org/manage/installing/index.html_ would be wrong, IMHO since we are not installing it, we are running it.

Would be http://docs.plone.org/manage better suited ?

@polyester @smcmahon what do you think ?

I would like to make sure that we have a good suited place, also with in mind that we may add snaps or other stuff one day :)

**Comment by polyester** [comment]
I would be in favor of http://docs.plone.org/manage, and then have /docker, /snap, /whateverthenextcoolthingis as subdirectories.

**Comment by svx** [comment]
Done in papyrus ! Docker docks will included in the next docs release !
