### ISSUE TITLE
Future ISort versions may need extra work to support plone import styleguide, or become incompatible

### ISSUE THREAD

**Issue by do3cc** [plone/documentation#567]
The latest version if sort, 4.3.x does not support plone coding styles. We can continue using 4.2.x for know without any issues.
The maintainer has hinted, that future 5.x versions might get an overhaul of the options to work more like jscs where you can name your preferred style. 

This is the future, this is no urgent pressing matter.

Now I open this ticket for discussing about the best reaction to this.

First for newcomers, a bit of history about this little part of the styleguides.
This was written in 2012, ISort didn't exist in that time. The styleguide for imports as it is, is probably not by accident, optimized to be complied to easily with most editor builtin tools (Lets forget about case insentive sorting)
Since we don't do manual import line sorting any more, I'll post the heretic question, if we want to continue having our own style guide for import lines, or if we want to adapt one of those style guides that might get included per default into ISort.
@hvelarde @gforcada 

For reference: https://github.com/timothycrosley/isort/issues/409

**Comment by do3cc** [comment]
My personal opinion: I don't care about which standard to follow, as long as it doesn't change to often. I don't even know how the other standards look. I am against adding a Plone preference style guide to ISort, because only no code is good code and having our own styleguide means, somebody has to maintain that.
I also don't mind throwing away our plone import line styleguide because it was based on facts that are not valid any more (the assumption that it happens manually, and thus should be as easy but as consistent as possible)

I gave up on trying to convince everybody that case sensitive sorting is better, because we already had so many files changed. Since then we at zumtobel got our gitlab_super_checker that allows us to update best practices in all projects at once. I see no reason why this should not work for the plone packages and collective packages that already have an isort configuration.

**Comment by gforcada** [comment]
First: isort maintainer already stated that breaking the sorting on a minor release was an error and a bugfix version will be released soon. So for the time being either pin to 4.2.2 or wait for the upcoming 4.2.4 release.

As for isort 5.0 with styleguides, as long as it's maintained within isort I don't see any problem at all. It will just make our current isort configuration on .isort.cfg of setup.cfg be turned into a single line (or that's what I would expect).

And specially given the way the project is being maintained I highly recommend to anyone to use it for any project, I started adding it on any project I'm contributing to.

As for the specifics of our styleguide: I totally like them because of its motto _"sort and forget"_. We have way better things to worry rather than how to sort imports, so given no technical problem (import side effects), that's the simplest way to sort something.

Actually I would be totally against removing isort usage within Plone as that's the only tool that can automatically sort imports without the least effort from developers.

That's the perfect first task to give to a newcomer for example.

**Comment by do3cc** [comment]
Uh, removing isort wasn't on the table. You might be mixing up stuff with previous discussions ;-)

**Comment by gforcada** [comment]
@do3cc then, yes I mixed things up :-)

**Comment by stevepiercy** [comment]
Closing as documentation is not the place for this discussion, but more amongst release managers.
