### ISSUE TITLE
Rewrite production/deployment

### ISSUE THREAD

**Issue by svx** [plone/documentation#601]
We are talking about this:
http://docs.plone.org/manage/deploying/production/ubuntu_production.html

Rewrite it in a way that it links to http://docs.plone.org/manage/installing/installation.html#install-the-operating-system-software-and-libraries-needed-to-run-plone.

Why:

Because currently we have to maintain versions on different places and as you can see under http://docs.plone.org/manage/deploying/production/ubuntu_production.html we have outdated versions

**Comment by mredigonda** [comment]
This issue is quite old now, is it still an issue? (I assume yes, since the Ubuntu Production doc is still there, but I ask just in case).

I would like to know what's the expected behavior when entering this site, I understand that either:
* The "Ubuntu Production" doc should be impossible to access, by redirecting the visitor to the new doc.
* The "Ubuntu Production" doc should still be accessible, but with nothing more than just a message saying "Hey, this doc is deprecated, go here now", pointing to the new doc.
* The "Ubuntu Production" doc should still be accessible, still having its contents, but with a big bold message at first saying that this doc is deprecated, and providing the link to the new doc.

Which of these three options should be implemented?

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/issues/1327
