### ISSUE TITLE
Fix links to plone.org

### ISSUE THREAD

**Issue by svx** [plone/documentation#618]
The launch of the new plone.org broke lots and lots of links, we need to fix that

**Comment by svx** [comment]
@polyester what are the current plans here, for now we have lots and lots of broken links, I do not want to link to old.plone.org, because I do not want to fix all this twice, I would like to think that I have a life besides - well - doing all this here ... :\

For the beginning how we would like to handle all the items in old/plone.org/kb we link to ?

**Comment by polyester** [comment]
hmm. 

for plone.org/documentation/kb/xxx:
Only https://old.plone.org/documentation/kb/manually-removing-local-persistent-utilities/ was working before the change, the other links were broken before already. Should be changed to internal link to  /manage/troubleshooting/manual-remove-utility as that had already been carried over.

all the other documentation/kb links were already not working, so no change there, they **should be updated/removed** eventually but situation remains unchanged.

more tricky what to do with the others.
- Links  to plone.org/documentation/manual/xxx look like they should either be removed (because hopelessly outdated) or replaced by internal links to docs.plone.org. 
- plone.org/documentation/faq/xxx : no idea, that's one hell of a mess. Luckily we only have three links.
  faq/locked-out should maybe go to 'troubleshooting'?
  faq/plone-logs maybe to Glossary?
  [faq/why-etcetera](https://old.plone.org/documentation/faq/why-doesnt-my-custom-content-type-show-up-in-add-menu) probably to Archetypes guide?
- plone.org/documentation/tutorial/xxx: they were not working before as well.
  -plone.org/documenation/how-to/xxx: they were not working before as well.

So most links were broken before, and thus also linking to old.plone.org won't help as they were broken on there as well. 
The 'manual' and 'tutorial' and 'how-to' ones need the most thought. We have replacements for them in the docs, but nothing automatic.

**Comment by svx** [comment]
So what would be the right link, to fix

The `plone.org Products <https://plone.org/products>`_, should I link to:

https://plone.org/download/add-ons/popular-add-ons

or 

https://plone.org/download/add-ons/all-plone-add-ons

For me it is a bit confusing on plone.org

**Comment by polyester** [comment]
that one to https://plone.org/download/add-ons/ which should remain the 'landing page' even if the algorithm or the method of showing add-ons changes.

For the individual links to (old) plone.org/products/xxxx, probably direct to the pypi pages of the products?

**Comment by svx** [comment]
https://github.com/plone/documentation/tree/svx_plone4_fix_addons needs to cherry-picked into the 4.3 branch

**Comment by svx** [comment]
done !

**Comment by 2silver** [comment]
Sorry, but I think this needs some love...
Most of the links to old.plone.org are "private" (or so).

A quick-check, with github search for ["documentation/kb"](https://github.com/plone/documentation/search?utf8=%E2%9C%93&q=documentation%2Fkb&type=) gives an "Insufficient Privileges" error

For example:
- [Reseting user password without emailing them](https://docs.plone.org/develop/plone/members/member_basics.html#reseting-user-password-without-emailing-them)
- [Analysing Data.fs content offline](https://docs.plone.org/develop/plone/persistency/storage.html#analysing-data-fs-content-offline)
- [Dashboard](https://docs.plone.org/develop/plone/functionality/dashboard.html#tutorial)

**Comment by tkimnguyen** [comment]
@2silver that's because those items are outdated/obsolete. The /documentation folder has been completely superseded by docs.plone.org

**Comment by tkimnguyen** [comment]
Wildcard Corp. has kindly added plone.org to its SiteImprove.com analysis subscription. I will post a list of plone.org broken links and we can start fixing or removing them.

**Comment by tkimnguyen** [comment]
@2silver but yeah those links to the old plone.org/documentation folder should be removed

**Comment by tkimnguyen** [comment]
@2silver would you mind making a pull request with your suggested changes to those pages and reopening this issue?
