### ISSUE TITLE
theming/barceloneta.html how to extend from barceloneta when not using the theme editor

### ISSUE THREAD

**Issue by djay** [plone/documentation#648]
currently unexplained.

**Comment by sverbois** [comment]
+1 to explain in the "Inheriting a new theme from Barceloneta" section how to compile the _styles.less_ when we work in a theme product.

**Comment by ebrehault** [comment]
The explanation provided in the current documentation here http://docs.plone.org/adapt-and-extend/theming/barceloneta.html#inheriting-a-new-theme-from-barceloneta should apply to both FS based and TTW based themes.

@sverbois, when creating a theme product, you can compile your less files using the theming editor: the theming editor allows to inspect FS-based themes, and since we have fixed https://github.com/plone/Products.CMFPlone/issues/1468, we can now use the Build CSS button in  such a theme, it will return the resulting CSS so you can copy/paste it into your sources.

Note: even if this approach is probably fine for a quick fix, it might be painful at start when you develop the all theme. In that case, 2 approaches:
- either work directly in a TTW theme, entirely with the theming editor, and we you are done, export it as a zip and put it in your sources
- either put the barceloneta resources in your theme temporarily, change the LESS import path (like `@import "++theme++barceloneta/less/barceloneta.plone.less";`) temporarily, and when you are done, clean that up.

**Comment by sverbois** [comment]
@ebrehault thank you for your detailed explanation.

**Comment by svx** [comment]
I guess we should improve http://docs.plone.org/adapt-and-extend/theming/barceloneta.html#inheriting-a-new-theme-from-barceloneta with the comment by @ebrehault ?

**Comment by svx** [comment]
@ebrehault ping ! :)
