### ISSUE TITLE
Do not link to Dexterity manual / Do not recommend ZopeSkel

### ISSUE THREAD

**Issue by rfleschenberg** [plone/documentation#775]
http://docs.plone.org/external/plone.app.dexterity/docs/prerequisite.html

This page recommends using ZopeSkel. I spent some time trying to follow these instructions, but to no avail. I was told on IRC that I should forget ZopeSkel and use mr.bob instead.

I don't have the exact steps to reproduce my various problems with ZopeSkel at hand anymore. If they are needed, please mention this, I will reproduce them again in that case.

My understanding of this is limited, but as it looks now, I think that these instructions should be updated to use mr.bob. That update should probably also be backported to the Plone 4 docs.

**Comment by djowett** [comment]
I think this documentation was fixed in https://github.com/plone/plone.app.dexterity/pull/222, *however* that fix sadly isn't pulled in to docs.plone.org with the /external reference [here](https://raw.githubusercontent.com/plone/documentation/5.0/adapt-and-extend/custom-ct/index.rst)

**Comment by svx** [comment]
Like always, this will turn up on docs.plone.org when we deploy a new build.

This will be most likely in the beginning of next week, *note* the **most likely** there are still some open issues which we need to fix first.

I am closing the ticket, since this is already solved in the docs of dexterity.

**Comment by djowett** [comment]
Thanks @svx, but what you are saying implies either:

a) you haven't deployed a new build for 6 months (since the above dexterity PR)
OR 
b) the external reference is broken somehow

Do you mind confirming whether a) is true, 'cos otherwise it's b) and we need that fixing bad!
No criticism of your valued work - which we are mucho grateful for!

**Comment by svx** [comment]
@djowett we have not deployed since months for various reasons as:

- papyrus [docs builder] was/is broken because of robot-framewrok and various other dependency  updates
- communication [mix up ?] about when 5.1 will be released
- docs team is for the moment [temporary] down to more or less 1 person
- lots of other things

Sorry, but there is a certain amount of stuff what you can do in small teams, taken that all that is done on volunteer basis after/next to our normal work.
