### ISSUE TITLE
Clarification of installation docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#804]
Currently our docs a bit confusing and mixed, which may a bit confusing, cause we are missing a structure.

What we have:

- https://docs.plone.org/manage/deploying/preparing.html
- https://docs.plone.org/manage/installing/installation.html
- https://docs.plone.org/external/ansible-playbook/

Currently it is hard and extra work to keep 'deploying' 'and installation' up 2 date, also it is not clear for everyone what the different is 

We should try to combine that partly with: https://github.com/plone/documentation/issues/758

**Comment by tkimnguyen** [comment]
A lot of this information is covered by each installation method anyway. I think we should consider deferring to what each installer includes for its documentation, since (a) it is otherwise duplication of information, and (b) difficult to maintain correctly in two places, since (c) the installers are changing rapidly.

**Comment by stevepiercy** [comment]
Closing. See https://6.docs.plone.org/install/index.html#install-plone
