### ISSUE TITLE
Inline code formatting

### ISSUE THREAD

**Issue by svx** [plone/documentation#818]
At the moment we have a interesting mix of various ways how we show inline code like how to run a certain command.

Currently we use techniques like:

"run command"

'run command'

``run command``

**run command**

*run $command*

This is somehow confusing for user. I propose that we settle on one and use that one through the whole documentation.

I would be in favor of using ``run command`` consistent through the whole docs, but this means we have to adjust certain bits where we use `` `` for highlighting stuff, which IMHO would be fine.

**Comment by gforcada** [comment]
Yes please!

**Comment by svx** [comment]
Okay, I checked again and before we start with this we need something for 'highlithing' stuff, for example we use now in some places this:

```
This ability is used by ``zc.buildout``
```
looks like: This ability is used by ``zc.buildout``

If we want to use back ticks for inlne code commands we need something else, should we make highlights bold ?

Meaning

```
 This ability is used by **zc.buildout**
```
looks like: This ability is used by **zc.buildout**

Summary
------------

Example1:

After you updated **buildout.cfg** with your changes, you have to re-run buildout again: ``/bin/buildout -v``

Or if we change it the way around (like Kubernetes does it)

Example2:

After you updated ``buildout.cfg`` with your changes, you have to re-run buildout again: **/bin/buildout -v**

Which one is better as in more clear and easier to understand ?

**Comment by svx** [comment]
@polyester @fredvd any suggestions ?

**Comment by polyester** [comment]
I'd say stay as close to the norm as we can. We use Restructured text, so:
- double backticks means "inline literal". Normally rendered using monospace font, and it would be good for code commands. 
- single backticks are "interpreted text". They are domain- or application- specific, so we can define we want this to mean "Highlight" and/or "particular names". 

So I would re-phrase the example as:
```
After you updated `buildout.cfg` with your changes, you have to re-run buiildout again: ``/bin/buildout -v``
```

Now, of course how that "looks" is a question of CSS, but it does make sense in a semantic way.
So: 
- inline code use double backticks
- names of programs and things you want to highlight, could be rendered as bold with a yellow background or anyway else: use single backticks
- things with heavy emphasis, conventionally rendered in bold: use double asterisk

**Comment by stevepiercy** [comment]
I think it's more important to use semantic markup first, and appearance second.

This in reST:

```
``Hello World!``
```

Becomes this in HTML:

```html
<code class="docutils literal"><span class="pre">Hello,</span> <span class="pre">world!</span></code>
```

```
`Hello World!`
```

```
<cite>Hello World!</cite>
```

```
**Hello World!**
```

```html
<strong>Hello World!</strong>
```

```
*Hello World!*
```

```html
<em>Hello World!</em>
```

For names of packages or files, you could create a special role, akin to what we do in Pyramid:

```
:app:`Pyramid`
```

And Sphinx has a bunch of other [inline semantic markup](http://www.sphinx-doc.org/en/latest/markup/inline.html#other-semantic-markup), including:

```
:file:`development.ini`
```

See also:
* http://pyramid-stevepiercy.readthedocs.io/en/style-guide/style-guide.html#inline-code
* http://pyramid-stevepiercy.readthedocs.io/en/style-guide/style-guide.html#strong
* http://pyramid-stevepiercy.readthedocs.io/en/style-guide/style-guide.html#the-role-app-pyramid

**Comment by svx** [comment]
@polyester OK if I render your proposal in reST I would get:

 After you updated *buildout.cfg* with your changes, you have to re-run buildout again: ``/bin/buildout -v``

I am fine with that, if we do that through the whole docs it would be a great improvement.

@stevepiercy I know, we already use inline markup for files and so on :), this here, is for me more a question about what would make sense, would be 'easy understandable' and consistent through the whole docs for inline commands, not code blocks, because currently we do not have this.

Well till now, I will update the style-guide and start fixing the first docs soon.

**Comment by stevepiercy** [comment]
@svx none of my examples are `.. code-block::`. All are inline markup. I used markdown in code blocks to show the reST and rendered HTML sources.

**Comment by svx** [comment]
Since we are on this topic, the next in line would be documentation about UI.

Currently, we mix here, too.

Examples:
```
Click on the right *Join Team*

Scroll down to the bottom of the screen and click "Save"

select 'Diazo theme support' and click 'Activate'

Click the ``Overrides`` tab
```

What would make sense here ? 
Bold but then in a different color ? I would like to keep bold as 'normal bold' :)

**Comment by stevepiercy** [comment]
Sphinx has `:guilabel:` and `:menuselection:` markup roles. See http://www.sphinx-doc.org/en/latest/markup/inline.html#other-semantic-markup

**Comment by svx** [comment]
I know, but I need a color :) I am bad with colors :)

Can someone point me to a nice and accessible friendly color which fits with our new 5.1 theme ?

Ping at @polyester @loechel :)

**Comment by svx** [comment]
In case if you wounder how the new theme will look like:

https://github.com/plone/sphinx.themes.plone/pull/49 has a screen-shot

**Comment by svx** [comment]
done ! Color and font-weight are adjusted !

**Comment by loechel** [comment]
@svx @polyester and @stevepiercy with the work on RestrictedPython I get conviced that code block examples should use:

    .. testcode:: 

instead of 

    .. code-block:: Python 

as then you could also check if this code is actually correct --> doctest in new. 

for all other I would be for ``code`` as inline.

@svx sorry I am good at implementing designs, but not at creating them or selecting good color schemas.

**Comment by stevepiercy** [comment]
Out of curiosity, is there a style guide that has both sample source code of reST and rendered HTML so that I can view samples of how things will look? I created [one for Pyramid](http://pyramid-stevepiercy.readthedocs.io/en/style-guide/) so that I could do that and share with designers.

I see the chosen color for the `:guilabel:` was a shade of blue. The navigation has a blue background. Links are a dark shade of blue. I interpret this as "blue things are clickable". A safe option is a high-contrast, dark shade of neutral grey. A professional designer might use a hue. It becomes difficult to read text with too many different styles applied. It's a tricky balance. I would have to see it.

@loechel do you mean to run doctest for all code blocks? I think that is asking too much. In Pyramid we use doctest only for a few code blocks where code is executed and output is shown. [Here are a couple places](https://github.com/Pylons/pyramid/commit/a470ff601182fed93446b8bfe4bc8707a8455949) and [how it renders](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#adding-methods-or-properties-to-a-request-object). Most of the time, however, execution and output is not desired or possible, like when we show a code-block snippet that requires imports.

**Comment by stevepiercy** [comment]
With the change to MyST and a new theme for Plone 6 docs, inline literals shall be coded as:

```
Example of `inline literal`.
```

Which renders as:

Example of `inline literal`.
