### ISSUE TITLE
LearnPlone.Org

### ISSUE THREAD

**Issue by ghost** [plone/documentation#854]
On some pages there is a reference to LearnPlone.org which now is training.plone.org, if I am correct.

e.g. https://docs.plone.org/working-with-content/using-collections/oldstyle/using-and-understanding-dates.html

Some examples mentioned - What's New listing - are not valid anymore.Since it's part of oldstyle
I don't know if it is worth updating them.

**Comment by svx** [comment]
Hi,

No, they have nothing to do which each other :)

If there are still LearnPlone resources in the docs, we need to remove/update these.

I did not checked, yet but indeed I guess some resources from LearnPlone are not valid anymore, there were for Plone2/3.

**Comment by svx** [comment]
@polyester @plone/framework-team Do we still have collections 'old style'  in Plone 5.1 ?

If not I'll remove that.

**Comment by jensens** [comment]
@svx IIRC when enabling ATContentTypes they are there for BBB reasons. But not by default. I would not document them or recommend to use them.

**Comment by svx** [comment]
OK, so what is the preference here ?

IMHO this is tricky, because we have to make sure it works for all scenarios.

For 'new sites' it is 'easy', do not use them, period.

But if you upgraded your site from an older version and you need ATContentTypes it would be nice to find that in the docs, right ?

So should we add a big huge, warning/note bla bla, telling it like this ?

**Comment by stevepiercy** [comment]
Closing as won't fix
