### ISSUE TITLE
Update: Docs about content management 

### ISSUE THREAD

**Issue by svx** [plone/documentation#861]
URL: https://docs.plone.org/develop/plone/content/index.html

Issue:

- Currently this document tells about Plone 3 and 4, Plone 5.x is completely missing. 
- It still tells about AT as a way to do stuff, which is logical cause this are still the old unchanged docs from Plone 3 and 4 :)

Solution:

- Add Plone 5.x
- Remove/Rewrite AT and tell this is not the way preferred way in Plone 5.x

**Comment by newbazz** [comment]
i want to take this issue.

**Comment by newbazz** [comment]
Sir as i am new to this can u guide me how to solve this.

**Comment by cewing** [comment]
@newbazz contributing to documentation is a wonderful way to help out with a project.  Thanks so much for offering!

We have [wonderful documentation](https://docs.plone.org/about/contributing.html) about how to contribute to our documentation.  I would suggest that you read through that page first to get an idea of how we work on our documentation and what you'll need to do to get started.  

After reading that, you might want to reach out to @svx here or in our [community website](https://community.plone.org) and ask him what he would like in terms of changes for these documents.  I think starting with a small change like adding Plone 5 to the list of versions of Plone on that first cover page would be a good place to start.  Then you can dive into more complex fixes, like removing references to Archetypes (AT) and adding information about Dexterity.  

Again, thanks for stepping up.  Please do not hesitate to ask questions and we will do everything in our power to help you get started.

**Comment by newbazz** [comment]
@cewing i went through the documentation, now can you please guide me how to solve this issue.

**Comment by newbazz** [comment]
@cewing i went through the documentation, now can you please guide me how to solve this issue.

**Comment by pigeonflight** [comment]
@newbazz... 
This may be an obvious question. Is it safe to assume that you've installed Plone and attempted to create a new content type? If so, are you clear on the differences between dexterity and archetypes?  This particular documentation issue will require that you understand the difference between older versions of Plone (3 and 4) and Plone 5.

**Comment by tkimnguyen** [comment]
I think the label FirstTimers may be misleading here because I don't believe it means this is a good issue for first time contributors to Plone; rather, it's an issue that needs to be resolved in order to help first timers / newcomers to Plone.

So @newbazz because you are new to Plone, it's not reasonable for you to expect to know enough about Plone 3 or 4 or Archetypes to be able to address those parts of the issue, and if you're not familiar with Plone 5, I think this is not at all an issue you should try to start with. Instead please consider reading through docs.plone.org and training.plone.org and let us know in the issues trackers if you find anything unclear or any errors in examples.

**Comment by newbazz** [comment]
@tkimnguyen thanks! coz i did not understand anything told by @pigeonflight .Can you plz tell me how to proceed after reading the doc.

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/issues/1445
