### ISSUE TITLE
Add 5.1 to upgrade guide

### ISSUE THREAD

**Issue by svx** [plone/documentation#881]
We do not have docs about upgrading to 5.1 in - > https://docs.plone.org/manage/upgrading/

This is IMHO a **blocker** for 5.1, we **have to make sure to have this at the time we release 5.1**

**Comment by svx** [comment]
Further: 

- change 'minor' release to be about Plone 5
- remove Plone 4 minor release
- add link/docs about upgrading from 4.x to 5.x

**Comment by svx** [comment]
@mauritsvanrees @pbauer This is done right ?

**Comment by mauritsvanrees** [comment]
Yes, it is done, as in: there now is at least *some* documentation on upgrading. Lots more could be added, but at least the structure is there, so that makes it easier for people to contribute once they run into problems and figure out how to solve them.

During the conference I started working on improving the docs, in this branch:
https://github.com/plone/documentation/tree/ploneconf2017-upgrade-guide-51
