### ISSUE TITLE
Investigate usage of sphinx-prompt

### ISSUE THREAD

**Issue by svx** [plone/documentation#908]
Currently we use

```
.. code-block:: shell
  cd foo
```
 for bash commands with an unselectable prompt.

This works fine for one-liner but not for multiple line with commands like

```
.. code-block:: shell
   cd foo
   touch bar
```
The result here will be that we *only* have the prompt shown on the first line ``cd foo``.

We should look at https://pypi.python.org/pypi/sphinx-prompt maybe this add-on fixes  this issue.

**Comment by loechel** [comment]
@svx sorry I don't understand what you try to solve.

    .. code-block:: <lang>

        code
        multiple lines

just defines which syntax highlighting should be used, it should never inject any additional symbols like ``$`` 

also you always should have an empty row between ``.. code-block:: <lang>`` and the first code line as Sphinx interprets directly connected lines as params for the macro.

So if you like to have 

    .. code-block:: shell

        $ cd foof
        $ touch bar

then please write it as such.

**Comment by svx** [comment]
Ahem ...

I really do not understand what you mean ...

Check our CSS we have a special setting for

.. code-block:: shell

This only works on the first line not on the second or third, etc, with the result that a script just looks weird.

BTW, I know how to write reST, there is no need to explain that to me...

**Comment by svx** [comment]
And @loechel  btw, please rad the title again, I wrote **investigate** as in try it out, and see.

I really do not get the point of your reaction, I try to improve something with looking at possibilities, there is IMHO no reason for such a unfriendly reaction ....

**Comment by loechel** [comment]
@svx I am sorry if that has sounded unfriendly, that was not intended. And I know that you know how to write reST, but if someone look at this ticket, they might get confused.

And investigate something sounds like trying to understand how something works and if that is useful for a project. As this is a issue ticket on the documentation I thaught you also are open for any feedback or input from someone. 

About the css settings, do you have an example page (Link) to see what you mean?

**Comment by loechel** [comment]
@svx sorry again, I think I get it.

you try to investigate a way to bypass an actual error on sphinxtheme.plone (https://github.com/plone/sphinxtheme.plone/blob/master/src/sphinxtheme/plone/plone_basic/static/css/plone_basic.css#L407-L414)

plone_basic.css seams to do things that it should not. We should clean that up. could you please open a ticket on sphinxtheme.plone if you would like to get the ``$`` prompt removed from css. It should be done on the code side if needed.

**Comment by svx** [comment]
@loechel adding the ``$`` to CSS is done on purpose.

The intention is that people should use ``.. code-block:: shell`` for code examples [cli/bash] like shell commands or short scripts.

This is also mentioned in our style-guide.

By doing so, the ``$`` will be added automatically on default.
We especially decided on that, cause we had a huge mix of shell/cli examples lots with ``$`` and lots without and also with mixed code-blocks like ``shell``, ``bash`` and some others.

Because of that we decided to tackle this with CSS.

State is, that this is working for one liners but thus not for multiple lines, since the ``$`` will only show up on the first line.

And since shell-prompt does that already and as far as I can tell (using it in one other project) is working nice the idea is to look how that works/look like with docs.plone.org.

**Comment by loechel** [comment]
ok I do understand why you / the group did it like that. 

Now by reading I also see and understand the **unselectable** Prompt.
If you think sphinx-prompt would help, go ahead. 

From my point of view, I would consider that more harmful than useful. 
Showing and reading (https://tink.uk/accessibility-support-for-css-generated-content/) content that would not be copyable could and will confuse enough users. Also understanding that copy something with explicite ``$`` Prompt will not work on CLI should be considered minimal knowledge, otherwise those users will produce more problems than solving some.

Additionally having multiple ways of doing the same thing --> syntax highlighting in documentation is also not pythonic ("There should be one -- and preferably only one -- obvious way to do it." --> https://www.python.org/dev/peps/pep-0020/). 

If you compare to our own reST style guide the one for Python Console is perfect https://docs.plone.org/about/rst-styleguide.html#syntax-highlighting --> ``.. code-block:: pycon`` 

    >>> Command \
    ...     hanging command
    Result

Users should think more on writing what they want to express --> "Explicit is better than implicit."

**Comment by loechel** [comment]
@svx another way that could be actual useful would be to look more closely into https://github.com/sphinx-doc/sphinx/blob/master/sphinx/directives/code.py#L97-L168 and see if it either mak sense to wrap each line with a span and introduce a ``:prompt: $`` option.

**Comment by loechel** [comment]
@svx sorry there is actually also an misunderstanding of the languages used: shell, bash, ... is intended for shell files if you would like to have a shell-prompt it would be console --> http://pygments.org/docs/lexers/#pygments.lexers.shell.BashSessionLexer

**Comment by svx** [comment]
@loechel thank you for your approval, I am so glad that you are OK with Me trying something out !

Quick question, next time I would like to fix a reST syntax error, should I ask you for permission first ?

So yeah, thanks a lot for all this stop energy, we are still talking different stuff, but yeah, thanks !
Congratulations I do not care anymore!

I now will happily spent my free time on other projects, thank you again for that !

**Comment by loechel** [comment]
I sincerely apologize if my comments have hurt you @svx. This was not intended. Of course you do not need anyones permission to try something. But if you ask explicitly by opening a ticket:

> We should look at https://pypi.python.org/pypi/sphinx-prompt maybe this add-on fixes this issue.

Then you must also assume that someone asks why and that those possible have a different opinion and think this approach is not good. 

It is about creating something better for the whole community. I see that in your idea and also in my constructive criticism. 
To be clear I do extremely like your engagement and enthusiasm to improve the documentation, this is fantastic. If we both wouldn't care, we would not discuss about something like that. 

So sorry again. I owe you a beer.

**Comment by stevepiercy** [comment]
I don't know whether Plone authors have this use case in the docs anywhere, but we often do this in Pyramid docs:

```rest
.. code-block:: bash

    # list contents of the directory
    $ ls -al
    # do something else
    $ another command
    # ... elided output from the command until finally ...
    # success!
    $ one more command
```

In which case using CSS or a Sphinx plugin to insert a prompt would complicate the author's intent to insert comments above commands. Yes, we could alternate with narrative, command/code-block, narrative, command/code-block, and so on, but sometimes that becomes noisy, disrupts flow, and lengthens the narrative.

We decided to use [literal prompts](https://docs.pylonsproject.org/projects/pyramid/en/latest/typographical-conventions.html#syntax-highlighting) to indicate commands in our source reST files. As an author I found this very helpful when I need to update commands for only one platform or language because I can search for the prompt when doing a find and replace: `$` for bash/Linux, `c:\>` for Windows, and so on. Yay for maintainability!

Fortunately the original Pyramid docs authors were consistent and diligent about using literal prompts. It sounds like that did not happen for Plone.

As far as the user side for consuming output, we (Pyramid authors) are unable to collect usage data and make assumptions about what is "best" for the user. Our discussions became subjective and opinionated. There is one advantage to the user by not using CSS or a plugin that I think has been overlooked: user choice. Maybe the user wants to select the prompt, maybe not, for whatever reason. Who are we to dictate what the user can or cannot do?

Thanks for the discussion.
