### ISSUE TITLE
Mixing configs with docs is not a good idea

### ISSUE THREAD

**Issue by polyester** [plone/documentation#929]
I'm uncomfortable with the inclusion of tox in https://github.com/plone/documentation/pull/920

For several reasons:

- It has from the beginning been a goal to have *only* docs in the documentation; having various bit of code (setup.py and such) and configuration in there is confusing. I know there are other configs in there, but we are really close to removing those (the robot-configs will go away today, the testing ones won't be necessary soon)
- The 'tox' process is far from complete, it does **not** give you the full documentation, as all the external pulls are missing, there are no robot-screenshots etcetera, so 'self-building' is not accurate as a description. People end up with incomplete documentation.
- It also gives you not the sort of quality checks that we are trying to integrate and make easy to use for writers.
- There are other ways to get the docs; work is nearly complete on the next generation of 'papyrus' that is simpler. Also docker-based alternatives which work on all operating systems. For getting a preview of your text with the plonedocs css there are editor plugins that are faster and friendlier.
- there are now two 'conf.py' instances: the one in papyrus and one in here. Over time they **will** diverge, as keeping them in sync will be forgotten. Yes it will be.
- the tox-build generates artifacts like https://github.com/plone/documentation/issues/926 that do not appear in a full build with papyrus. I do not have the energy and time to go digging into yet another toolchain set to see if the problem is in Sphinx, tox, or somewhere in between.
- again, 'docs as code' does not mean 'code in my docs' ;-)

So, while I admire the effort that went into it, and see the need of 'a simpler way for power-users to build and test docs' , I strongly feel that that should be done with a little more planning. I feel this will become yet another quick 'dev-centric' semi-fix that will be more work over time.

**Comment by svx** [comment]
Also, please remember, most of the time it is not necessary to fire up Sphinx.
If you as (example), work on one document, where you fix a typo, a link or a reST issue, you want to see the changes in that file and in that file only, since you are working on that **one** file.

For this you do not need the *overkill* of Sphinx, as I mentioned in my talk, for stuff like this you can use your editor.

There are for example reST plugins for Vim, Sublime, Atom, etc.
This add-ons can be configured to show your reST in Sphinx 'valid' HTML even with your own CSS. 

This is faster, you even can use 'instant preview' mode, meaning see you changes as you type, plus you get all the linters you want or need.
