### ISSUE TITLE
LIVE docs: plone.api content in rendered docs empty

### ISSUE THREAD

**Issue by jensens** [plone/documentation#938]
https://docs.plone.org/develop/plone.api/docs/api/content.html

and all other api pages

![screenshot from 2017-11-09 12 31 05](https://user-images.githubusercontent.com/157140/32603408-eafad808-c549-11e7-9b16-bd58b985406a.png)

cc @svx @plone/documentation-team

**Comment by svx** [comment]
@jensens These sites are empty because the sites are also empty in: https://github.com/plone/plone.api/tree/master/docs/api

Here is only a *automodule* used, I am not sure if that has todo the removal of Plone from the documentation build process or something else.

I am even not sure if that worked before.

@polyester any ideas ?

**Comment by svx** [comment]
Ok, so it is getting interesting.

If I check a old version, meaning which was build with papyrus out of the 5 branch it works.

The difference here is that Plone and more stuff got removed from the buildout in the 5.1 branch.

This needs to get tested more, but this is not all.

If I clone the plone.api repo and run ```tox -e docs``` I get yet again another version of the docs with different content.

Fun times !

This needs more research, I can see the point of setting up docs via docstrings, as this is a 'programmer thing' no offense. !! :)

Yet, again looking at it as a documentation person, that is **not the best idea**, so to say :)

We need to think how we solve that in a smart way I guess.

@polyester hints, ideas, suggestions ? :)

**Comment by polyester** [comment]
Not really. 
Although automodule should not have much to do with Plone, but more with Sphinx. Maybe the previous sphinx had more modules, like sphinx.ext.autodoc  being pulled in. That's the only one that this should depend on, not so much Plone.

**Comment by svx** [comment]
OK, here we go !

This is kind of annoying but because of the way how the docs of plone.api are done, we have to add Plone back to the buildout, which is *really not that nice*.

If I add Plone back like:

```
[buildout]
extends =
    checkouts-documentation.cfg
    http://dist.plone.org/release/5.1-latest/versions.cfg
...
...
...
[sphinx-build]
recipe = zc.recipe.egg
eggs =
    Sphinx
    sphinxtheme.plone
    pyenchant
    sphinxcontrib-spelling
    sphinxcontrib.gist
    sphinxcontrib-osexample
    Plone
```
It is working again:
![plone-api-pap](https://user-images.githubusercontent.com/358860/32614110-cc7ec556-c56c-11e7-8434-a9b4eb1cce18.png)

I tried to use plone.api in place of Plone:

```
[sphinx-build]
recipe = zc.recipe.egg
eggs =
    Sphinx
    sphinxtheme.plone
    pyenchant
    sphinxcontrib-spelling
    sphinxcontrib.gist
    sphinxcontrib-osexample
    plone.api
```
But this basically pull in Plone, the only difference I get lots of version conflicts and the build stops with errors.

I guess for now I will add Plone back and for the long term we have to think about another solution.

@polyester do you agree ?

**Comment by polyester** [comment]
I do remember that plone.api [was running on readthedocs](https://readthedocs.org/projects/ploneapi/), which definitely was not pulling in Plone, so I still think it needs sphinx.ext.autodoc more than Plone.

But have no time today to check out if just putting that in as an egg, or explicitly in conf.py, would be enough. Will try Saturday.

**Comment by polyester** [comment]
Might be a good idea to shoot @zupo a question; he devised the doc thingie, so will know what it needs.

**Comment by svx** [comment]
@polyester I added sphinx.ext.autodoc to the buildout that changes nothing, without adding Plone

Also, how is that supposed to work, only adding this will not help because it needs a source from where it can get the docstrings.

We are dumping everything besides the docs from the repo, so there is nothing how Sphinx can get the docstrings.

Publishing to RTD works different, have a look at the plone.api repo :)

That works different than our use case :)

As I said, already above,  I tried it only with the egg, that gave lots of version conflict buildout was not working :)

**Comment by polyester** [comment]
I thought it would get the docstrings from plone.api itself, as that's all it needs, but needs to be non-sparse checkout (so full source code, not just /docs dir). 

But yeah, if we're in a hurry just add Plone back in for now, I'll investigate over the weekend.

**Comment by svx** [comment]
Yeah, possible but than this would be for the next version of papyrus, starting now to fiddle more on the old setup is not that cool, there are enough other things to do.
I would rather focus on the new version.

I mean, adding Plone is not nice, but it is temporary anyway.

**Comment by svx** [comment]
@jensens New build is online !

![plone-api-fixed](https://user-images.githubusercontent.com/358860/32616691-4270a3be-c573-11e7-8423-dcc04374b77b.png)

**Comment by jensens** [comment]
Thanks a lot!

**Comment by zupo** [comment]
> I do remember that plone.api was running on readthedocs, which definitely was not pulling in Plone, so I still think it needs sphinx.ext.autodoc more than Plone

Actually, I remember that RTD did pull in Plone ... or maybe plone.api did not depend on Plone yet back then?
