### ISSUE TITLE
should caution against zexp export/import

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#972]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

Need to add warnings about zexp export/import at https://docs.plone.org/develop/plone/content/importexport.html

**Comment by tkimnguyen** [comment]
I guess there is a statement there about identical versions of add-ons and packages. But need to say this method works only in very limited circumstances, and emphasize that other more general methods should be tried first.

**Comment by idgserpro** [comment]
A statement about memory errors would be nice as well, if your object is too big.

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module OFS.ObjectManager, line 588, in manage_exportObject
  Module ZODB.ExportImport, line 66, in exportFile
  Module ZODB.utils, line 112, in cp
MemoryError: out of memory
```

IIRC, there's an issue as well if your `/tmp` partition is too small because the exporting/importing of zexps uses `/tmp` as well. (http://plone.293351.n2.nabble.com/IOError-importing-large-plone-site-with-plenty-of-disk-space-td5115159.html)

**Comment by vedantc98** [comment]
I've made a PR for this issue. :)
